"""empty message

Revision ID: 05a32035af31
Revises: bee018b0ab0f
Create Date: 2023-12-30 09:48:37.986804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a32035af31'
down_revision = 'bee018b0ab0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Trains', schema=None) as batch_op:
        batch_op.alter_column('depart',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.alter_column('arrival',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Trains', schema=None) as batch_op:
        batch_op.alter_column('arrival',
               existing_type=sa.String(length=60),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('depart',
               existing_type=sa.String(length=60),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
