"""empty message

Revision ID: 33482b456bc8
Revises: 05a32035af31
Create Date: 2023-12-30 10:06:00.853428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33482b456bc8'
down_revision = '05a32035af31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Destination', schema=None) as batch_op:
        batch_op.alter_column('train_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Destination', schema=None) as batch_op:
        batch_op.alter_column('train_no',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
